services:

  central-log-server:
    container_name: central-log-server
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        GIT_TAG: v9.0.2
        GIT_REPO: https://github.com/AetherBreaker/aeth_ext.git
    restart: on-failure:3
    expose:
      - 8080
    volumes:
      - type: bind
        source: /data/central_log_server_files
        target: /app/persisted_data
    environment:
      - ALERTS_EMAIL=info@sweetfiretobacco.com
      - ALERTS_EMAIL_PWD=${ALERTS_EMAIL_PWD:?}
      - ALERTS_RECIPIENTS=["jacob.ogden@sweetfiretobacco.com"]
      - HEARTBEAT_SLUG=central-log-server
    networks:
      coolify:
        aliases:
          - central-log-server
    labels:
      - "traefik.http.middlewares.logauth.basicauth.users=admin:$2a$05$9CWerMKGo26UptRyu.CMxOajlnkDwUrRe9frfdQhCYgh0Iy17/n6W"
    healthcheck:
      test:
        - CMD
        - /app/.venv/bin/devkit-container
        - healthcheck
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  coolify:
    external: true
