#:schema logging_config_schema.json

version                  = 1
disable_existing_loggers = false

[formatters.preferred]
  "()"      = "aeth_ext.logging.bases.SmartColumnFormatter"
  columns   = ["{libpath}", "[{asctime}]", "{levelname: >8}", "{message}"]
  separator = " | "
  datefmt   = "runtime://timestamp_format"

[loggers.paramiko]
  level = "WARNING"

[loggers.fontTools]
  level = "WARNING"

[root]
  level    = "runtime://root_level"
  handlers = []
