#:schema logging_config_schema.json
# Per-run variant of server_hierarchy_daily.toml; see that file for context.

version                  = 1
disable_existing_loggers = false

[formatters.preferred]
  "()"      = "aeth_ext.logging.bases.SmartColumnFormatter"
  columns   = ["{libpath}", "[{asctime}]", "{levelname: >8}", "{message}"]
  separator = " | "
  datefmt   = "runtime://timestamp_format"

[handlers.debug_file]
  "()"        = "aeth_ext.logging.setup.make_per_run_file_handler"
  filename    = "runtime://debug_log_path"
  backupCount = 30
  level       = "DEBUG"
  formatter   = "preferred"

[handlers.info_file]
  "()"        = "aeth_ext.logging.setup.make_per_run_file_handler"
  filename    = "runtime://info_log_path"
  backupCount = 30
  level       = "INFO"
  formatter   = "preferred"

[root]
  level    = "runtime://root_level"
  handlers = ["debug_file", "info_file"]
