# Standard library imports
import pickle
import sys
from collections.abc import Callable
from types import CellType, EllipsisType, FunctionType, ModuleType, NotImplementedType
from typing import Any, override

DEFAULT_PROTOCOL = ...
_PICKLE_BY_VALUE_MODULES = ...
_DYNAMIC_CLASS_TRACKER_BY_CLASS = ...
_DYNAMIC_CLASS_TRACKER_BY_ID = ...
_DYNAMIC_CLASS_TRACKER_LOCK = ...
PYPY = ...
builtin_code_type = ...
if PYPY:
  builtin_code_type = ...
_extract_code_globals_cache = ...

def register_pickle_by_value(module: ModuleType) -> None: ...
def unregister_pickle_by_value(module: ModuleType) -> None: ...
def list_registry_pickle_by_value() -> set[Any]: ...

if sys.version_info >= (3, 14): ...
else: ...
STORE_GLOBAL = ...
DELETE_GLOBAL = ...
LOAD_GLOBAL = ...
GLOBAL_OPS = ...
HAVE_ARGUMENT = ...
EXTENDED_ARG = ...
_BUILTIN_TYPE_NAMES = ...

def is_tornado_coroutine(func: Callable[..., Any]) -> bool: ...
def subimport(name: str) -> ModuleType: ...
def dynamic_subimport(name: str, vars: Any) -> ModuleType: ...  # noqa: A002
def instance[In_T](cls: type[In_T]) -> In_T: ...

@instance
class _empty_cell_value:  # noqa: N801
  @override
  @classmethod
  def __reduce__(cls) -> str: ...  # pyright: ignore[reportIncompatibleMethodOverride]

_DATACLASSE_FIELD_TYPE_SENTINELS = ...

class Pickler(pickle.Pickler):
  _dispatch_table = ...
  dispatch_table = ...
  @override
  def dump(self, obj: Any) -> None: ...
  def __init__(self, file, protocol=..., buffer_callback=...) -> None: ...

  if not PYPY:
    dispatch = ...
    def reducer_override(
      self, obj
    ) -> (
      tuple[type[type], tuple[None]]
      | tuple[type[type], tuple[EllipsisType]]
      | tuple[type[type], tuple[NotImplementedType]]
      | tuple[Callable[..., type[type] | Any], tuple[Any]]
      | tuple[
        Callable[..., Any],
        tuple[tuple[type, ...], str, str, dict[str, Any], str, str | Any, None],
        tuple[dict[str, Any], dict[Any, Any]],
        None,
        None,
        Callable[..., Any],
      ]
      | tuple[
        Callable[..., Any | type],
        tuple[type[Any], Any, Any, dict[Any, Any], str | Any, None],
        tuple[dict[str, Any], dict[Any, Any]],
        None,
        None,
        Callable[..., Any],
      ]
      | NotImplementedType
      | tuple[
        Callable[..., FunctionType],
        tuple[Any, Any, None, None, tuple[CellType | Any, ...] | None],
        tuple[dict[str, Any], dict[str, Any]],
        None,
        None,
        Callable[..., None],
      ]
    ): ...

  else:
    dispatch = ...
    def save_global(self, obj, name=..., pack=...) -> None: ...
    def save_function(self, obj, name=...) -> None: ...
    def save_pypy_builtin_func(self, obj) -> None: ...

def dump(obj, file, protocol=..., buffer_callback=...) -> None: ...
def dumps(obj, protocol=..., buffer_callback=...) -> bytes: ...

CloudPickler = Pickler
